apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hackfest-devfile-sample-go-basic-kz2y
  namespace: rhn-support-rick-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:e4adfbf8d415d6d46a4ada7bd6212b0674823f21deded83282e3fe6b1155f702
        name: my-go
        resources: {}
status: {}
