apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hackfest-devfile-sample-go-basic-kz2y
  namespace: rhn-support-rick-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:ab6ddc94baaea1d1b247c555f927b24ef108009147ea3348d7c037ed47c5c7c5
        name: my-go
        resources: {}
status: {}
