apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hackfest-devfile-sample-go-basic-kz2y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hackfest-devfile-sample-go-basic-kz2y
    app.kubernetes.io/part-of: hackfest-go2
  name: hackfest-devfile-sample-go-basic-kz2y
  namespace: rhn-support-rick-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: hackfest-devfile-sample-go-basic-kz2y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: hackfest-devfile-sample-go-basic-kz2y
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:ab6ddc94baaea1d1b247c555f927b24ef108009147ea3348d7c037ed47c5c7c5
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
