apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hackfest-devfile-sample-go-basic-kz2y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hackfest-devfile-sample-go-basic-kz2y
    app.kubernetes.io/part-of: hackfest-go2
  name: hackfest-devfile-sample-go-basic-kz2y
  namespace: rhn-support-rick-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: hackfest-devfile-sample-go-basic-kz2y
status:
  loadBalancer: {}
